title: Ruiqing Zang's Homepage
page-top-title: Ruiqing Zang
top-section-bg-text: Applied Physics
home-subtitle: Ruiqing Zang&ensp;|&ensp;臧瑞卿
copyright-text: '&copy; Ruiqing Zang 2024-2025. All Rights Reserved.'
